# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef42f82d4ecbcbcd9588ab7739ec7f6afe4a65a10e30eefb645a8212095a0aea07ff0e92de0bfe999a975532e54a13d7e7f8bcb404234548d71a2938a7508078

test:
  secret_key_base: 8d7d034ab5e30e31cefca8d709bbd12b8e7389f428a9abda9d1ad02ebe87593463f2d9c229bec82cd7b1f7a0c2643f64a40f6ae9d3a621779bb73828a3be66a7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
